### ISSUE TITLE
Enable Immutability by default

### ISSUE THREAD

**Issue by codecudi** [rubrikinc/terraform-aws-rubrik-cloud-cluster-elastic-storage#11]
Immutability is required for the recoverability feature in cluster versions >= v.8.0.1. It's already enabled by default for Terraform deployments, but the documentation should reflect that.

Cf. [CDM-399509](https://rubrik.atlassian.net/browse/CDM-399509)

**Comment by DamaniN** [comment]
Fixed by #12
