### ISSUE TITLE
S3 bucket ACL for <bucket>: AccessControlListNotSupported Errors

### ISSUE THREAD

**Issue by SpikeyWeasel** [rubrikinc/terraform-aws-rubrik-cloud-cluster-elastic-storage#4]
Amazon have changed default behaviour for S3 buckets as of April 2023 as per: https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html

The module creates an ACL that is now no longer applicable and causes errors of the form below:

Plan: 1 to add, 0 to change, 0 to destroy.
module.rubrik-cluster.module.rubrik_cluster.aws_s3_bucket_acl.cces-s3-bucket-acl: Creating...
╷
│ Error: error creating S3 bucket ACL for : AccessControlListNotSupported: The bucket does not allow ACLs

**Comment by DamaniN** [comment]
This was fixed as a by product of commit e45b6e9 where we removed setting ACLs on the bucket.
