### ISSUE TITLE
Ensure cluster disk type used for root EBS volume and if gp3 used specify throughput

### ISSUE THREAD

**Issue by SpikeyWeasel** [rubrikinc/terraform-aws-rubrik-cloud-cluster-elastic-storage#6]
As confirmed with Mark Csepke gp3 requires 250MB/s throughput.  gp2 does not require this to be set.
Also use the cluster_disk_type variable is not applied to the root block device volume type. So even if you specify gp3 you still get a gp2 root volume.

I've raised a pull request to rectify (https://github.com/rubrikinc/terraform-aws-rubrik-cloud-cluster-elastic-storage/pull/5)

**Comment by DamaniN** [comment]
Fixed by #5
